[package]
name = "stark101-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.14.0"
num = "0.4.3"
rand = "0.9.0"
sha256 = "1.6.0"
